# Mongodb configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# Email configuration
sendgrid.api-key=${SENDGRID_API_KEY}
sendgrid.from-email=osman.n2@icloud.com

# Application info
app.base.url=http://localhost:8080

# Cloudinary information
cloudinary.cloud-name=dlsytszzz
cloudinary.api-key=${CLOUD_KEY}
cloudinary.api-secret=${CLOUD_SECRET}

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=604800000

# PayPal Developer configuration
paypal.mode=sandbox
paypal.client-id=${PAYPAL_CLIENT_ID}
paypal.client-secret=${PAYPAL_SECRET}
